### PR TITLE
Item GUI Rendering fix

### LINKED ISSUE #9: EatingAnimation mod breaks potion CIT (Optifine)
If you have a resource pack that adds CIT (Custom Item Textures) to potions using Optifine, the potions in the GUI will not use the CIT provided by the resource pack. The potions held in the players hands, on the ground, and in item frames will use the CIT, but in the inventory, they will not.

The mod doesn't effect all CIT. As shown in the clips, CIT for axolotl buckets are unaffected.

I'm unsure why the mod breaks potion CIT considering the mod doesn't give potions a drinking animation.

**Videos:**
[Without EatingAnimations mod.](https://streamable.com/5tlztz)
[With EatingAnimations mod.](https://streamable.com/i8ocwj)

### PR DESCRIPTION
**Pull request by AkashiiKun**
Fixes https://github.com/Theoness1/EatingAnimation/issues/9
Now CIT Resewn and Optifine's CIT should work on GUI.

### CODE REVIEW

**Comment by Leolele99** [comment]
Hey,

I tried to apply this to my own for, but it seems like the getModel() method cannot be resolved.
Is there anything specific required to get it to work?

**Review by DerLeole — CHANGES_REQUESTED** [review]
Code as of rn is not compiling.
Change this.getModel() to this.getHeldItemModel() in line 49.

Tested in a large modpack to work.

**Comment by AkashiiKun** [comment]
Look at innerRenderInGui method and you'll see it's exactly getModel().

**Comment by AkashiiKun** [comment]
I was looking at yarn mappings.

**Comment by Leolele99** [comment]
Wait then this makes no sense.
I did a clean fork of the project, as is, merged your fork into mine, and got an error.
Do you want a screenshot to investigate?

I did try it with my updated variation and it then works as intended.

**Comment by Leolele99** [comment]
Just checked again, and for 1.17.1 (and I think 1.18.1) the innerRenderInGui() method also uses getHeldItemModel().
image

**Comment by AkashiiKun** [comment]
The problem is that somehow it didn't upload this.
Screenshot_20220315_154545

**Comment by Leolele99** [comment]
I just tried your newest fix and even rebuilt all my sources, but I still get an error, this time that ItemRender.java doesnt even contain a method called getModel().

Can you check if your sources are up to date?

**Comment by AkashiiKun** [comment]
They are up do date, just cloned it and built it.

**Comment by Leolele99** [comment]
Huh, curious, what IDE and general MC modding setup are you using?
If I compare both the code blocks of our screenshots, it seems like our decompilers/deobfuscators translated the sources slightly differently?

**Comment by AkashiiKun** [comment]
Intellij Idea.

> Huh, curious, what IDE and general MC modding setup are you using? If I compare both the code blocks of our screenshots, it seems like our decompilers/deobfuscators translated the sources slightly differently?

Intellij Idea, Minecraft 1.18.1.

**Comment by AkashiiKun** [comment]
Screenshot_20220315_155418

**Comment by Leolele99** [comment]
I was previously, but I am now back in 1.17.1, as I actually need that version.

That could be it then. I tried earlier in 1.18.1 which didnt work, which could be due to the missing shadow you now fixed.

**Comment by Leolele99** [comment]
Well, in closing then:
Yours will probably work for 1.18.1.
For 1.17.1 just replace the getModel() with getHeldItemModel() and it should work!

**Comment by Julienraptor01** [comment]
@Theoness1 will this be merged soon ? Because i really like your mod but CIT incompatibility breaks many things in my resource pack.

**Comment by Julienraptor01** [comment]
I have tested the fork and i didn't see any problem

**Comment by Julienraptor01** [comment]
@Theoness1 why didn't you merge this in the 1.8 update ?

**Comment by Theoness1** [comment]
> @Theoness1 why didn't you merge this in the 1.8 update ?

sorry, i forgot ;(
I'll check later
Does the code just disable the animation for the renamed model?

**Comment by Julienraptor01** [comment]
> > @Theoness1 why didn't you merge this in the 1.8 update ?
> 
> sorry, i forgot ;( I'll check later Does the code just disable the animation for the renamed model?

Yes it disable the animation and CIT is still broken for items like apple by example in the inventory.
But at least every other CIT works than food works and CIT for food works everywhere except in the inventory.

**Comment by Julienraptor01** [comment]
So this fix isn't perfect but it's better than nothing

**Comment by AkashiiKun** [comment]
Maybe removing the whole thing would render even the CITR food textures.

**Comment by Theoness1** [comment]
> Maybe removing the whole thing would render even the CITR food textures.

?

**Comment by EGOIST1372** [comment]
so whats the state of this pull request? is it gonna implement or looking for another fix?
@Theoness1 @Julienraptor01 @AkashiiKun

**Comment by Julienraptor01** [comment]
> so whats the state of this pull request? is it gonna implement or looking for another fix?
> @Theoness1 @Julienraptor01 @AkashiiKun 

I think this should be implemented as a temporary fix until a better fix is present

**Comment by EGOIST1372** [comment]
@Julienraptor01 so this is still an issue and since it closed mean not implemented in 1.19 version, right?

**Comment by AkashiiKun** [comment]
Is closed because i deleted my fork.

**Comment by Julienraptor01** [comment]
> Is closed because i deleted my fork.

I still have a copy of your modified code on my own fork.
But my fork isn't updated to 1.19.
(i'll do it soon, when my exams ends tho)
And because i didn't saw any change to the code, i think the issue is still present.

**Comment by Julienraptor01** [comment]
> @Julienraptor01 so this is still an issue and since it closed mean not implemented in 1.19 version, right? 

But yes this is still an issue

**Comment by Theoness1** [comment]
I'm currently working on another mod, when I finish it, I'll see what happens with the render

**Comment by Theoness1** [comment]
bruh

**Comment by Theoness1** [comment]
bruh

**Comment by PinkGoosik** [comment]
bruhh

**Comment by PinkGoosik** [comment]
> Just checked again, and for 1.17.1 (and I think 1.18.1) the innerRenderInGui() method also uses getHeldItemModel(). image

@Leolele99 what is this theme?

**Comment by Julienraptor01** [comment]
Why bruh ?

**Comment by PinkGoosik** [comment]
we came to the same solution as this pull request

**Comment by PinkGoosik** [comment]
we should have looked into this pull request 😅

**Comment by Theoness1** [comment]
sorry im learning C# D:

**Comment by pavelbat3** [comment]
Doesnt works
image

**Pull request closed without merging**
