### PR TITLE
Update pack.mcmeta to use the support the new changes in the texture …

### PR DESCRIPTION
**Pull request by I-No-oNe**
…system

It's useful, so from now the pack will be "updated" for feature version of Minecraft.

### CODE REVIEW

**Comment by I-No-oNe** [comment]
@Theoness1 any thoughts?

**Comment by Theoness1** [comment]
> @Theoness1 any thoughts?

That doesn't work.

**Comment by I-No-oNe** [comment]
@Theoness1 It's working in the new versions(1.20.2-1.20.4 etc)

**Comment by Theoness1** [comment]
> @Theoness1 It's working in the new versions(1.20.2-1.20.4 etc)

Nope, I checked this and no resourcepack in resourcepack settings

**Pull request closed without merging**
